name: Unit tests

on:
  workflow_call:
    inputs:
      os:
        description: "Operating System to build on"
        required: true
        type: string
      pyver:
        description: "Python version to build on"
        required: true
        type: string
    secrets:
      PYTKET_REMOTE_IBM_CLOUD_INSTANCE:
        description: "PYTKET_REMOTE_IBM_CLOUD_INSTANCE"
        required: false
      PYTKET_REMOTE_IBM_CLOUD_TOKEN:
        description: "PYTKET_REMOTE_IBM_CLOUD_TOKEN"
        required: false
      PYTKET_REMOTE_BRAKET_ACCESS_KEY_ID:
        description: "PYTKET_REMOTE_BRAKET_ACCESS_KEY_ID"
        required: false
      PYTKET_REMOTE_BRAKET_ACCESS_KEY_SECRET:
        description: "PYTKET_REMOTE_BRAKET_ACCESS_KEY_SECRET"
        required: false
      PYTKET_REMOTE_BRAKET_REGION:
        description: "PYTKET_REMOTE_BRAKET_REGION"
        required: false
      PYTKET_REMOTE_BRAKET_BUCKET:
        description: "PYTKET_REMOTE_BRAKET_BUCKET"
        required: false
      PYTKET_REMOTE_BRAKET_FOLDER:
        description: "PYTKET_REMOTE_BRAKET_FOLDER"
        required: false
      PYTKET_REMOTE_IQM_API_TOKEN:
        description: "PYTKET_REMOTE_IQM_API_TOKEN"
        required: false


jobs:
  unit-tests:
    name: Unit tests
    runs-on: ${{ inputs.os }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.4.20"
          enable-cache: true
      - name: Install Python ${{ inputs.pyver }}
        run: uv python install ${{ inputs.pyver }}
      - name: Setup dependencies
        run: uv sync --python ${{ inputs.pyver }}
      - name: Pytest
        env:
          PYTKET_RUN_REMOTE_TESTS: 1
          PYTKET_RUN_REMOTE_TESTS_PROD: 1
          PYTKET_REMOTE_QUANTINUUM_EMULATORS_ONLY: 1
          PYTKET_REMOTE_IBM_CLOUD_INSTANCE: ${{ secrets.PYTKET_REMOTE_IBM_CLOUD_INSTANCE }}
          PYTKET_REMOTE_IBM_CLOUD_TOKEN: ${{ secrets.PYTKET_REMOTE_IBM_CLOUD_TOKEN }}
          PYTKET_REMOTE_BRAKET_ACCESS_KEY_ID: ${{ secrets.PYTKET_REMOTE_BRAKET_ACCESS_KEY_ID }}
          PYTKET_REMOTE_BRAKET_ACCESS_KEY_SECRET: ${{ secrets.PYTKET_REMOTE_BRAKET_ACCESS_KEY_SECRET }}
          PYTKET_REMOTE_BRAKET_REGION: ${{ secrets.PYTKET_REMOTE_BRAKET_REGION }}
          PYTKET_REMOTE_BRAKET_BUCKET: ${{ secrets.PYTKET_REMOTE_BRAKET_BUCKET }}
          PYTKET_REMOTE_BRAKET_FOLDER: ${{ secrets.PYTKET_REMOTE_BRAKET_FOLDER }}

        run: uv run pytest
